// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

type HelloServiceHandler struct {
}

func NewHelloServiceHandler() *HelloServiceHandler {
	return &HelloServiceHandler{}
}
