// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package hello

import "micode.be.xiaomi.com/systech/soa/thrift"

type HelloServiceInf interface {
	SetTimeout(connTimeout, readTimeout uint32)
	SetContext(ctx *thrift.XContext)
	SetMethodTimeout(method string, timeout uint32)
	SetBalanceKey(balanceKey string)
	SetParentRpcId(rpcId int32)
	SetLogId(logId int64)

	// Parameters:
	//  - Name
	HelloWorld(name string) (r *Result_, errRet error)
}
